services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: mongo:7.0
    container_name: quepo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quepoDB
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
