
# docker-compose.yml

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      URLDB: "mongodb://db:27017/quepoDB"
      TOKEN_SECRET: "TokenTotalmenteSecreto"
      TOKEN_EXPIRES: "18000000"
      ALLOWED_ORIGINS: "http://62.175.45.209:5000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      # Para Vue + Vite
      VITE_API_URL: "http://62.175.45.209:8000"
    restart: unless-stopped

  db:
    image: mongo:7.0
    container_name: quepo-mongo
    # MongoDB NO expuesto al exterior por seguridad
    environment:
      MONGO_INITDB_DATABASE: quepoDB
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    restart: unless-stopped

volumes:
  mongo_data:
